/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet;

/**
 *
 * @author apacot
 */
public class PoidsIdeal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private String Nom;
    private String Prenom;
    private double imc;
    private double poids;
    private double taille;
    private int age;
    final private double imcs[] = {16.5,18.5,25,30,35,40};
    final private String corpulences[] = {"Famine", "Maigreur", "Normale", "Surpoids", "Obésité modérée", "Obésité sévère", "Obésité morbide"};
    final private int NBIMC = 6;
    final private int NBCORPULENCE =7;
            
    
    public PoidsIdeal() 
    {
        initComponents();       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupSexe = new javax.swing.ButtonGroup();
        jPanelInformations = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabelSexe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioFemme = new javax.swing.JRadioButton();
        jRadioHomme = new javax.swing.JRadioButton();
        jLabelAge = new javax.swing.JLabel();
        jSpinnerAge = new javax.swing.JSpinner();
        jLabelPoids = new javax.swing.JLabel();
        jSpinnerPoids = new javax.swing.JSpinner();
        jLabelTaille = new javax.swing.JLabel();
        jSpinnerTaille = new javax.swing.JSpinner();
        jButtonSuite = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAfficheur = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calcul poids ideal");
        setMaximumSize(new java.awt.Dimension(530, 620));
        setMinimumSize(new java.awt.Dimension(530, 620));
        setPreferredSize(new java.awt.Dimension(530, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelInformations.setLayout(new java.awt.GridLayout(6, 2));

        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNom.setText("Nom");
        jLabelNom.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanelInformations.add(jLabelNom);
        jPanelInformations.add(jTextFieldNom);

        jLabelPrenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrenom.setText("Prénom");
        jLabelPrenom.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanelInformations.add(jLabelPrenom);
        jPanelInformations.add(jTextFieldPrenom);

        jLabelSexe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSexe.setText("Sexe");
        jLabelSexe.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanelInformations.add(jLabelSexe);

        jPanel1.setLayout(new java.awt.GridLayout());

        ButtonGroupSexe.add(jRadioFemme);
        jRadioFemme.setText("Femme");
        jPanel1.add(jRadioFemme);

        ButtonGroupSexe.add(jRadioHomme);
        jRadioHomme.setText("Homme");
        jPanel1.add(jRadioHomme);

        jPanelInformations.add(jPanel1);

        jLabelAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAge.setText("Age");
        jLabelAge.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanelInformations.add(jLabelAge);

        jSpinnerAge.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        jPanelInformations.add(jSpinnerAge);

        jLabelPoids.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPoids.setText("Poids");
        jPanelInformations.add(jLabelPoids);

        jSpinnerPoids.setModel(new javax.swing.SpinnerNumberModel(15.0d, 15.0d, 300.0d, 0.1d));
        jPanelInformations.add(jSpinnerPoids);

        jLabelTaille.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTaille.setText("Taille");
        jPanelInformations.add(jLabelTaille);

        jSpinnerTaille.setModel(new javax.swing.SpinnerNumberModel(1.5d, 0.5d, 3.0d, 0.01d));
        jPanelInformations.add(jSpinnerTaille);

        getContentPane().add(jPanelInformations);
        jPanelInformations.setBounds(20, 10, 330, 170);

        jButtonSuite.setText("Suite");
        getContentPane().add(jButtonSuite);
        jButtonSuite.setBounds(140, 190, 70, 25);

        jPanel2.setLayout(null);

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        jButton1.setText("Poids idéal devine");
        jPanel3.add(jButton1);

        jButton2.setText("Poids idéal lorentz");
        jPanel3.add(jButton2);

        jButton3.setText("Poids Ideal lorentz /age");
        jPanel3.add(jButton3);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(30, 10, 230, 100);

        jTextAreaAfficheur.setColumns(20);
        jTextAreaAfficheur.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAfficheur);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 350, 130);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 300, 370, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoidsIdeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroupSexe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSuite;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPoids;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelTaille;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelInformations;
    private javax.swing.JRadioButton jRadioFemme;
    private javax.swing.JRadioButton jRadioHomme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAge;
    private javax.swing.JSpinner jSpinnerPoids;
    private javax.swing.JSpinner jSpinnerTaille;
    private javax.swing.JTextArea jTextAreaAfficheur;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
