ARDUINO_VARIANT = lolin32
SERIAL_PORT = /dev/ttyUSB0
ARDUINO_ARCH = esp32
ARDUINO_LIBS = WiFi/src AsyncTCP/src ESPAsyncWebServer/src
USER_LIBS = WiFi/src AsyncTCP/src ESPAsyncWebServer/src 
include /opt/Esp8266-Arduino-Makefile/espXArduino.mk