ARDUINO_VARIANT = lolin32
SERIAL_PORT = /dev/ttyUSB0
ARDUINO_ARCH = esp32
ARDUINO_LIBS = BME280/src PocketGeiger/src wifi/src SD/src SPI/src FS/src
USER_LIBS = BME280/src PocketGeiger/src wifi/src SD/src SPI/src FS/src
include /opt/Esp8266-Arduino-Makefile/espXArduino.mk