ARDUINO_VARIANT = lolin32
SERIAL_PORT = /dev/ttyUSB0
ARDUINO_ARCH = esp32
ARDUINO_LIBS = SD/src SPI/src FS/src LITTLEFS/src
USER_LIBS = SD/src SPI/src FS/src LITTLEFS/src
include /opt/Esp8266-Arduino-Makefile/espXArduino.mk