/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimClavier;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author apacot
 */
public class FenClavier extends javax.swing.JFrame {

    /**
     * Creates new form FenClavier
     */
    public FenClavier() {
        initComponents();
        touche1.addActionListener(new GestionnaireTouche());
        touche2.addActionListener(new GestionnaireTouche());
        touche3.addActionListener(new GestionnaireTouche());
        touche4.addActionListener(new GestionnaireTouche());
        touche5.addActionListener(new GestionnaireTouche());
        touche6.addActionListener(new GestionnaireTouche());
        touche7.addActionListener(new GestionnaireTouche());
        touche8.addActionListener(new GestionnaireTouche());
        touche9.addActionListener(new GestionnaireTouche());
        touche0.addActionListener(new GestionnaireTouche());

    }

    public class GestionnaireTouche implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            //recuperation de l'objet à l'origine de l'evenement
            Object src = e.getSource();
            //si l'objet est un boutton
            if (src instanceof JButton) {
                //recupérer le texte du boutton
                String texteDeLaTouche = ((JButton) src).getText();
                //ajouter le texte du bouton au texte deja present
                if ((textMess.getText().length()) < 4) {
                    textMess.setText(textMess.getText() + texteDeLaTouche);
                }              
                // dans la zone textMess
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textMess = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        fondClavier = new javax.swing.JPanel();
        touche1 = new javax.swing.JButton();
        touche2 = new javax.swing.JButton();
        touche3 = new javax.swing.JButton();
        touche4 = new javax.swing.JButton();
        touche5 = new javax.swing.JButton();
        touche6 = new javax.swing.JButton();
        touche7 = new javax.swing.JButton();
        touche8 = new javax.swing.JButton();
        touche9 = new javax.swing.JButton();
        toucheEtoile = new javax.swing.JButton();
        touche0 = new javax.swing.JButton();
        toucheD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clavier");
        setBackground(java.awt.Color.lightGray);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(220, 250));
        setMinimumSize(new java.awt.Dimension(220, 250));
        setPreferredSize(new java.awt.Dimension(220, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        textMess.setEditable(false);
        textMess.setBackground(new java.awt.Color(0, 153, 204));
        textMess.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(textMess);
        textMess.setBounds(20, 0, 170, 30);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        fondClavier.setBackground(new java.awt.Color(0, 0, 0));
        fondClavier.setMaximumSize(new java.awt.Dimension(120, 160));
        fondClavier.setMinimumSize(new java.awt.Dimension(120, 160));
        fondClavier.setPreferredSize(new java.awt.Dimension(120, 160));
        fondClavier.setLayout(new java.awt.GridLayout(4, 3, 3, 3));

        touche1.setBackground(new java.awt.Color(255, 255, 255));
        touche1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche1.setText("1");
        touche1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche1.setMaximumSize(new java.awt.Dimension(26, 26));
        touche1.setMinimumSize(new java.awt.Dimension(26, 26));
        touche1.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche1);

        touche2.setBackground(new java.awt.Color(255, 255, 255));
        touche2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche2.setText("2");
        touche2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche2.setMaximumSize(new java.awt.Dimension(26, 26));
        touche2.setMinimumSize(new java.awt.Dimension(26, 26));
        touche2.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche2);

        touche3.setBackground(new java.awt.Color(255, 255, 255));
        touche3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche3.setText("3");
        touche3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche3.setMaximumSize(new java.awt.Dimension(26, 26));
        touche3.setMinimumSize(new java.awt.Dimension(26, 26));
        touche3.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche3);

        touche4.setBackground(new java.awt.Color(255, 255, 255));
        touche4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche4.setText("4");
        touche4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche4.setMaximumSize(new java.awt.Dimension(26, 26));
        touche4.setMinimumSize(new java.awt.Dimension(26, 26));
        touche4.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche4);

        touche5.setBackground(new java.awt.Color(255, 255, 255));
        touche5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche5.setText("5");
        touche5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche5.setMaximumSize(new java.awt.Dimension(26, 26));
        touche5.setMinimumSize(new java.awt.Dimension(26, 26));
        touche5.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche5);

        touche6.setBackground(new java.awt.Color(255, 255, 255));
        touche6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche6.setText("6");
        touche6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche6.setMaximumSize(new java.awt.Dimension(26, 26));
        touche6.setMinimumSize(new java.awt.Dimension(26, 26));
        touche6.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche6);

        touche7.setBackground(new java.awt.Color(255, 255, 255));
        touche7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche7.setText("7");
        touche7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche7.setMaximumSize(new java.awt.Dimension(26, 26));
        touche7.setMinimumSize(new java.awt.Dimension(26, 26));
        touche7.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche7);

        touche8.setBackground(new java.awt.Color(255, 255, 255));
        touche8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche8.setText("8");
        touche8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche8.setMaximumSize(new java.awt.Dimension(26, 26));
        touche8.setMinimumSize(new java.awt.Dimension(26, 26));
        touche8.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche8);

        touche9.setBackground(new java.awt.Color(255, 255, 255));
        touche9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche9.setText("9");
        touche9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche9.setMaximumSize(new java.awt.Dimension(26, 26));
        touche9.setMinimumSize(new java.awt.Dimension(26, 26));
        touche9.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche9);

        toucheEtoile.setBackground(new java.awt.Color(255, 255, 255));
        toucheEtoile.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        toucheEtoile.setText("*");
        toucheEtoile.setMargin(new java.awt.Insets(2, 2, 2, 2));
        toucheEtoile.setMaximumSize(new java.awt.Dimension(26, 26));
        toucheEtoile.setMinimumSize(new java.awt.Dimension(26, 26));
        toucheEtoile.setPreferredSize(new java.awt.Dimension(26, 26));
        toucheEtoile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toucheEtoileMouseClicked(evt);
            }
        });
        fondClavier.add(toucheEtoile);

        touche0.setBackground(new java.awt.Color(255, 255, 255));
        touche0.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        touche0.setText("0");
        touche0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        touche0.setMaximumSize(new java.awt.Dimension(26, 26));
        touche0.setMinimumSize(new java.awt.Dimension(26, 26));
        touche0.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(touche0);

        toucheD.setBackground(new java.awt.Color(255, 255, 255));
        toucheD.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        toucheD.setText("#");
        toucheD.setMargin(new java.awt.Insets(2, 2, 2, 2));
        toucheD.setMaximumSize(new java.awt.Dimension(26, 26));
        toucheD.setMinimumSize(new java.awt.Dimension(26, 26));
        toucheD.setPreferredSize(new java.awt.Dimension(26, 26));
        toucheD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toucheDMouseClicked(evt);
            }
        });
        fondClavier.add(toucheD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondClavier, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondClavier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 170, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toucheDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toucheDMouseClicked
        // TODO add your handling code here:
        textMess.setText("");
    }//GEN-LAST:event_toucheDMouseClicked
    private void toucheEtoileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toucheEtoileMouseClicked
        // TODO add your handling code here:
        if("1234".equals(textMess.getText()))
        {
            textMess.setText("");
            textMess.setBackground(Color.green);
        }
        else
        {
            textMess.setText("");
            textMess.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_toucheEtoileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenClavier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondClavier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textMess;
    private javax.swing.JButton touche0;
    private javax.swing.JButton touche1;
    private javax.swing.JButton touche2;
    private javax.swing.JButton touche3;
    private javax.swing.JButton touche4;
    private javax.swing.JButton touche5;
    private javax.swing.JButton touche6;
    private javax.swing.JButton touche7;
    private javax.swing.JButton touche8;
    private javax.swing.JButton touche9;
    private javax.swing.JButton toucheD;
    private javax.swing.JButton toucheEtoile;
    // End of variables declaration//GEN-END:variables
}
